---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: cosi-driver-credentials
  namespace: cosi
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: objectstorage-provisioner
  data:
   - secretKey: ACCESS_KEY
     remoteRef:
       key: secret/data/hub/cosi-driver
       property: access_key
   - secretKey: ACCOUNT_NAME
     remoteRef:
       key: secret/data/hub/cosi-driver
       property: account_name
   - secretKey: ENDPOINT
     remoteRef:
       key: secret/data/hub/cosi-driver
       property: endpoint
   - secretKey: PC_SECRET
     remoteRef:
       key: secret/data/hub/cosi-driver
       property: pc_secret
   - secretKey: SECRET_KEY
     remoteRef:
       key: secret/data/hub/cosi-driver
       property: secret_key
