---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: cosi-driver-credentials
  namespace: cosi
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: objectstorage-provisioner
  dataFrom:
  - extract:
      key: secret/data/hub/cosi-driver