---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: cosi-driver-credentials
  namespace: cosi
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: objectstorage-provisioner
    template:
      metadata:
        annotations:
          cosi.storage.k8s.io/authors: Nutanix Inc
          cosi.storage.k8s.io/license: Apache V2
          cosi.storage.k8s.io/support: https://github.com/kubernetes-sigs/container-object-storage-api
        labels:
          app.kubernetes.io/component: driver-ntnx
          app.kubernetes.io/name: cosi-driver-ntnx
          app.kubernetes.io/part-of: container-object-storage-interface
          app.kubernetes.io/version: main
      type: Opaque
   data:
   - secretKey: ACCESS_KEY
     remoteRef:
       key: secret/data/hub/cosi-driver
       property: access_key
   - secretKey: ACCOUNT_NAME
     remoteRef:
       key: secret/data/hub/cosi-driver
       property: account_name
   - secretKey: ENDPOINT
     remoteRef:
       key: secret/data/hub/cosi-driver
       property: endpoint
   - secretKey: PC_SECRET
     remoteRef:
       key: secret/data/hub/cosi-driver
       property: pc_secret
   - secretKey: SECRET_KEY
     remoteRef:
       key: secret/data/hub/cosi-driver
       property: secret_key

