---
global:
  pattern: multicluster-devsecops

  cicd:
    namespace: devsecops-ci

  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

  secure-registry:
    namespace: "openshift-storage"

  imageregistry:
    account: jesseagonzalez
    hostname: quay.io
    type: quay

  git:
    hostname: github.com
    account: jesse-gonzalez
    username: jesse-gonzalez
    email: jesse.gonzalez@nutanix.com
    dev_revision: main

  cosi-driver:
    account_name: "cosiaccount"
    endpoint: "ntnx-objects.ntnxlab.local"
    
  quay:
    # Needs to be set consistently between hub and spoke clusters
    # TODO: Move back to the hub chart, store in a configmap, have an ACM policy distribute to spoke clusters, have spoke look up from configmap
    org:
      name: devel
      email: devel@myorg.com
    repo: example
  opp: false

main:
  clusterGroupName: hub
