apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.quay.configBundleSecret.name }}-v2
  namespace: {{ .Values.quay.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: Validate=false
type: Opaque
data:
  test: '{{ (lookup "config.openshift.io/v1" "Ingress" "" "cluster").spec }}'
  host: '{{ (lookup "v1" "Secret" "quay-enterprise" "quay-registry-bucket-creds").data }}'
