apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.quay.configBundleSecret.name }}-v2
  namespace: {{ .Values.quay.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
type: Opaque
stringData:
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secretObj := ((lookup "v1" "Secret" "quay-enterprise" "quay-registry-bucket-creds").data.BucketInfo | b64dec | fromJson) }}
  {{- $secretData := (get $secretObj "data") | fromJson }}
  # set $jwtSecret to existing secret data or generate a random one when not exists
  {{- $jwtSecret := (get $secretData "BucketInfo") | b64dec | fromJson }}
  secretObjTest: {{ $secretObj | quote }}
  secretDataTest: {{ $secretData | quote }}
  jwt-secret: {{ $jwtSecret | quote }}
  ##host: 'index ((lookup "v1" "Secret" "quay-enterprise" "quay-registry-bucket-creds").data.BucketInfo | b64dec | fromJson).spec.secretS3 "endpoint"'
