apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.quay.configBundleSecret.name }}-v2
  namespace: {{ .Values.quay.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
type: Opaque
stringData:
  secretObjTest: |
    '{{ (lookup "v1" "Secret" "quay-enterprise" "quay-registry-bucket-creds").data | toJson }}'
  ##host: 'index ((lookup "v1" "Secret" "quay-enterprise" "quay-registry-bucket-creds").data.BucketInfo | b64dec | fromJson).spec.secretS3 "endpoint"'
