apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.quay.configBundleSecret.name }}-v2
  namespace: {{ .Values.quay.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: "Validate=false,ServerSideApply=true"
type: Opaque
data:
  #quaySecretTest: 'index ((lookup "v1" "Secret" "quay-enterprise" "quay-registry-bucket-creds").data.BucketInfo | b64dec | fromJson).spec.secretS3 "endpoint"'
  quayInitTokenTest: {{ ((lookup "v1" "Secret" "quay-enterprise" "quay-init-token").data).password | b64enc | quote }}
