{{- $secret := "obc-observability-bucket-creds" }}
{{- $secretData := .Files.Get (printf "secrets/%s.json" $secret) | b64dec | fromJson }}
{{- $value := index $secretData.data "BucketInfo" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: thanos-test-secret
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  bucket: {{ $value }}


