---
apiVersion: v1
kind: Secret
metadata:
  name: thanos-test-secret
  namespace: open-cluster-management-observability
type: Opaque
data:
  bucket: '{{ `{{ fromSecret "cosi" "objectstorage-provisioner" "ACCESS_KEY" | b64enc | quote }}` }}'


