---
apiVersion: v1
kind: Secret
metadata:
  name: htpasswd-secret
  namespace: open-cluster-management-observability
type: Opaque
data:
  auth: |
    '{{ `{{ (lookup "v1" "Secret" "cosi" "quay-creds").data }}` }}'
