---
apiVersion: v1
kind: Secret
metadata:
  name: thanos-test-secret
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: '{{ `{{ (lookup "v1" "Secret" "cosi" "quay-creds").data | toJson | quote }}` }}'