---
apiVersion: v1
kind: Secret
metadata:
  name: htpasswd-secret
  namespace: open-cluster-management-observability
type: Opaque
data:
  test.json: '{{ `{{ (lookup "v1" "Secret" "cosi" "quay-creds").data | toJson | quote }}` }}'