{{- $secret := "grafana-config" }}
{{- $secretData := .Files.Get (printf "secrets/%s.json" $secret) | b64dec | fromJson }}
{{- $value := index $secretData.data "grafana-config.ini" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: thanos-test-secret
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  bucket: {{ $value }}


