kind: BucketClaim
apiVersion: objectstorage.k8s.io/v1alpha1
metadata:
  name: quay-registry-bucket
spec:
  bucketClassName: nutanix-objects
  protocols:
  - s3
---
kind: BucketAccess
apiVersion: objectstorage.k8s.io/v1alpha1
metadata:
  name: quay-registry-ba
spec:
  bucketClaimName: quay-registry-bucket
  protocol: s3
  bucketAccessClassName: nutanix-objects-bac
  credentialsSecretName: quay-registry-bucket-creds
