---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  # This is the external image registry (e.g. quay.io/docker)
  name: cosi-driver
  namespace: devsecops-ci
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: cosi-driver
    template:
  dataFrom:
  - extract:
      key: {{ .Values.cosi-driver.key }}
