# The policy needs to be added to the ACM HUB and then it will be pushed on all clusters
# except the HUB (see placementrule on the bottom)
{{ if .Values.clusterGroup.isHubCluster }}
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-cosi-driver-secret
  namespace: devsecops-ci
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: SkipPrune
    argocd.argoproj.io/sync-wave: "15"
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: cosi-driver-configpolicy
          annotations:
            apps.open-cluster-management.io/deployables: "secret"
        spec:
          remediationAction: enforce
          severity: medium
          namespaceSelector:
            include:
              - default
              - devsecops-ci
              - cosi
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: Secret
                type: Opaque
                metadata:
                  name: cosi-driver-credentials
                  namespace: cosi
                apiVersion: v1
                data:
                  access_key: '{{ `{{hub fromSecret "devsecops-ci" "cosi-driver-credentials" "access_key" hub}}` }}'
                  account_name: '{{ `{{hub fromSecret "devsecops-ci" "cosi-driver-credentials" "account_name" hub}}` }}'
                  endpoint: '{{ `{{hub fromSecret "devsecops-ci" "cosi-driver-credentials" "endpoint" hub}}` }}'
                  pc_secret: '{{ `{{hub fromSecret "devsecops-ci" "cosi-driver-credentials" "pc_secret" hub}}` }}'
                  secret_key: '{{ `{{hub fromSecret "devsecops-ci" "cosi-driver-credentials" "secret_key" hub}}` }}'
            - complianceType: musthave
              objectDefinition:
                kind: Secret
                type: Opaque
                metadata:
                  name: cosi-driver-credentials
                  namespace: devsecops-ci
                apiVersion: v1
                data:
                  access_key: '{{ `{{hub fromSecret "devsecops-ci" "cosi-driver-credentials" "access_key" hub}}` }}'
                  account_name: '{{ `{{hub fromSecret "devsecops-ci" "cosi-driver-credentials" "account_name" hub}}` }}'
                  endpoint: '{{ `{{hub fromSecret "devsecops-ci" "cosi-driver-credentials" "endpoint" hub}}` }}'
                  pc_secret: '{{ `{{hub fromSecret "devsecops-ci" "cosi-driver-credentials" "pc_secret" hub}}` }}'
                  secret_key: '{{ `{{hub fromSecret "devsecops-ci" "cosi-driver-credentials" "secret_key" hub}}` }}'
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: cosi-driver-placement-binding
  namespace: devsecops-ci
placementRef:
  name: cosi-driver-placement
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-cosi-driver
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
# We need to run this on any managed cluster but not on the HUB
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: cosi-driver-placement
  namespace: devsecops-ci
spec:
  # This will go to both devel and secured clusters
  clusterSelector:
    # Using matchExpression because I need it in more than one clusterGroup/cluster-group
    matchExpressions:
      - key: clusterGroup
        operator: In
        values:
          - hub
          - devel
          - prod
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
{{ end }}